[global]
shortname = "Gochan"
subtitle = "A modern imageboard engine written in Go!"
recentpostsnum = 10 #Number of most recent posts (for homepage)

#Optional server-side rendered frontend for gochan
[frontend]
enabled = true
staticdir = "/static"

[database]
host = "localhost"
port = "5432"
user = "admin"
password = "changethepassword"
database = "gochan"
sslmode = "disable"

#RESTful API for gochan backend
[api]
enabled = false
recentpostsnum = 5  # Controls how many posts the [/api/posts/mostrecent] endpoint returns (default=15)
sessiontokensize = 32